version: '3.5'

services:
  ant-design-pro_web:
    image: oiar/antd-nginx
    ports:
      - 8090:80
    container_name: 'project_web'
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

#volumes:
#  dist:
